Views created with their respective routes
BC-MAY-21-ROR/kata-07-reloj-checador-k7-n21-t1 pull request #11
Opened 2022-01-07 00:08 UTC by YxMARCKxY

# Description
We pass the views to the format required by rails and we relate each view with its respective path.

In addition to making use of the helpers in rails such as:
    -image_tag
    -stylesheet_link_tag
    -javascript_pack_tag
    -link_to

2022-01-07 00:27 UTC, LuisGomez89 submitted a review, later dismissed

2022-01-07 02:44 UTC, YilKanda requested changes
Be careful, in this Pull Request commits appear from your [PR #9](https://github.com/BC-MAY-21-ROR/kata-07-reloj-checador-k7-n21-t1/pull/9/commits), you need to separate yourself from those commits, and only be above your main branch.

2022-01-11 23:46 UTC, EduardoGHdez commented on time-clock/app/javascript/packs/timer-script.js
> +window.onload = function () {
It'd be nice if we can refactor this functionality to use Stimulus JS to follow the new Rails conventions

2022-01-11 23:52 UTC, EduardoGHdez approved these changes, later dismissed
LGTM

2022-01-12 02:35 UTC, YilKanda commented on time-clock/app/assets/stylesheets/layouts.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
If you don't occupy it, delete it.

2022-01-12 02:35 UTC, YilKanda commented on time-clock/app/helpers/index_helper.rb
> +end
If you don't occupy it, delete it.

2022-01-12 02:35 UTC, YilKanda commented on time-clock/app/helpers/layouts_helper.rb
> +end
If you don't occupy it, delete it.

2022-01-12 02:35 UTC, YilKanda commented on time-clock/app/views/pages/branches.html.erb
> +          </tr>
Is this repeated code necessary?

2022-01-12 02:35 UTC, YilKanda commented on time-clock/app/views/pages/employees.html.erb
> +          </tr>
Is this repeated code necessary?

2022-01-12 02:35 UTC, YilKanda commented on time-clock/config/database.yml
> +  timeout: 5000
It is not recommended to leave this file on GitHub, I recommend you place it in the .gitignore, and instead replace it with a database.yml.example file.

2022-01-13 01:05 UTC, EduardoGHdez commented on time-clock/Gemfile.lock
> +  stimulus-rails
I think you need to run `bundle` again, so the lock gets updated and this dependency gets removed 👍🏽

2022-01-13 01:05 UTC, EduardoGHdez commented on time-clock/.gitignore
> +./config/database.yml
Is this actually working?
I mean, I just made some changes to this file, and adding the dot won't make anything I think

2022-01-13 01:06 UTC, EduardoGHdez approved these changes
Small comments, none of them should be considered as a blocker 👍🏽 

LGTM

2022-01-13 01:18 UTC, merged